[workspace]
members = ["crates/cli","crates/core"]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Ahmed Said"]
license = "MIT"
repository = "https://github.com/TheJacksonLaboratory/xenium-panel-convert"
version = "0.11.0"
description = "A command-line utility for converting files to the formats accepted by the 10x Genomics Xenium Panel Designer"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.104"
camino = {version = "1.2.6", features = ["serde1"] }
csv = "1.4.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = { version = "1.1.6", default-features = false, features = ["std", "serde", "parse"] }
phf_codegen = { version = "0.14.0", features = ["ptrhash"] }
phf = { version = "0.14.0", features = ["ptrhash"] }
clap = { version = "4.6.7", features = ["derive"] }
hdf5-metno = { version = "0.15.0", features = ["static", "zlib", "lzf"] }
ndarray = { version = "0.17.2" }
sprs = { version = "0.11.5", default-features = false }
strum = { version = "0.28.0", features = ["derive"] }
tempfile = "3.27.0"
thiserror = { version = "2.0.21" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
implicit_hasher = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[workspace.lints.rust]
unreachable_pub = "warn"
dead_code_pub_in_binary = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
unnameable_types = "warn"
unit_bindings = "warn"

[profile]
release = { lto = true, codegen-units = 1, strip = true }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
